// Code generated by "stringer -type Kind -trimprefix T type.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Txxx-0]
	_ = x[TINT8-1]
	_ = x[TUINT8-2]
	_ = x[TINT16-3]
	_ = x[TUINT16-4]
	_ = x[TINT32-5]
	_ = x[TUINT32-6]
	_ = x[TINT64-7]
	_ = x[TUINT64-8]
	_ = x[TINT-9]
	_ = x[TUINT-10]
	_ = x[TUINTPTR-11]
	_ = x[TCOMPLEX64-12]
	_ = x[TCOMPLEX128-13]
	_ = x[TFLOAT32-14]
	_ = x[TFLOAT64-15]
	_ = x[TDECIMAL64-16]
	_ = x[TDECIMAL128-17]
	_ = x[TBOOL-18]
	_ = x[TPTR-19]
	_ = x[TFUNC-20]
	_ = x[TSLICE-21]
	_ = x[TARRAY-22]
	_ = x[TSTRUCT-23]
	_ = x[TCHAN-24]
	_ = x[TMAP-25]
	_ = x[TINTER-26]
	_ = x[TFORW-27]
	_ = x[TANY-28]
	_ = x[TSTRING-29]
	_ = x[TUNSAFEPTR-30]
	_ = x[TIDEAL-31]
	_ = x[TNIL-32]
	_ = x[TBLANK-33]
	_ = x[TFUNCARGS-34]
	_ = x[TCHANARGS-35]
	_ = x[TSSA-36]
	_ = x[TTUPLE-37]
	_ = x[TRESULTS-38]
	_ = x[NTYPE-39]
}

const _Kind_name = "xxxINT8UINT8INT16UINT16INT32UINT32INT64UINT64INTUINTUINTPTRCOMPLEX64COMPLEX128FLOAT32FLOAT64DECIMAL64DECIMAL128BOOLPTRFUNCSLICEARRAYSTRUCTCHANMAPINTERFORWANYSTRINGUNSAFEPTRIDEALNILBLANKFUNCARGSCHANARGSSSATUPLERESULTSNTYPE"

var _Kind_index = [...]uint8{0, 3, 7, 12, 17, 23, 28, 34, 39, 45, 48, 52, 59, 68, 78, 85, 92, 101, 111, 115, 118, 122, 127, 132, 138, 142, 145, 150, 154, 157, 163, 172, 177, 180, 185, 193, 201, 204, 209, 216, 221}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
