// Copyright 2025 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package strconv

import "unsafe"

// FormatDecimal64 converts a decimal64 value to a string.
// The format fmt and precision prec follow the same rules as FormatFloat:
//
//	'f'	decimal point, no exponent, e.g. 123.456
//	'e'	scientific notation, e.g. 1.23456e+02
//	'g'	whichever of 'e' or 'f' produces shorter output
//
// The special precision -1 uses the minimum number of digits
// to represent the value exactly.
func FormatDecimal64(d decimal64, fmt byte, prec int) string {
	return string(AppendDecimal64(nil, d, fmt, prec))
}

// AppendDecimal64 appends the string form of the decimal64 value d,
// as generated by FormatDecimal64, to dst and returns the extended buffer.
func AppendDecimal64(dst []byte, d decimal64, fmt byte, prec int) []byte {
	b := *(*uint64)(unsafe.Pointer(&d))
	sign, exp, coeff, special := bid64Unpack(b)
	if special != 0 {
		return appendSpecial(dst, sign, special)
	}
	return appendDecimalDigits(dst, sign, exp, coeff, fmt, prec)
}

// FormatDecimal128 converts a decimal128 value to a string.
// The format fmt and precision prec follow the same rules as FormatDecimal64.
func FormatDecimal128(d decimal128, fmt byte, prec int) string {
	return string(AppendDecimal128(nil, d, fmt, prec))
}

// AppendDecimal128 appends the string form of the decimal128 value d,
// as generated by FormatDecimal128, to dst and returns the extended buffer.
func AppendDecimal128(dst []byte, d decimal128, fmt byte, prec int) []byte {
	p := (*[2]uint64)(unsafe.Pointer(&d))
	lo, hi := p[0], p[1]
	sign, exp, coeff, special := bid128Unpack(lo, hi)
	if special != 0 {
		return appendSpecial(dst, sign, special)
	}
	// Convert uint128 coefficient to decimal digits.
	return appendDecimalDigits128(dst, sign, exp, coeff, fmt, prec)
}

// ParseDecimal64 converts a string to a decimal64 value.
// It recognizes decimal floating-point literals, "NaN", "Inf", and "+Inf"/"-Inf".
func ParseDecimal64(s string) (decimal64, error) {
	d, err := parseDecimal64(s)
	if err != nil {
		return d, syntaxError("ParseDecimal64", s)
	}
	return d, nil
}

// ParseDecimal128 converts a string to a decimal128 value.
// It recognizes decimal floating-point literals, "NaN", "Inf", and "+Inf"/"-Inf".
func ParseDecimal128(s string) (decimal128, error) {
	d, err := parseDecimal128(s)
	if err != nil {
		return d, syntaxError("ParseDecimal128", s)
	}
	return d, nil
}

// --- BID64 unpacking ---

const (
	specialNaN = 1
	specialInf = 2
)

// bid64Unpack extracts sign, biased exponent, coefficient, and special value flag
// from a BID64-encoded uint64.
func bid64Unpack(b uint64) (sign int, exp int, coeff uint64, special int) {
	sign = int(b >> 63)
	if b&0x7c00000000000000 == 0x7c00000000000000 {
		return sign, 0, 0, specialNaN
	}
	if b&0x7800000000000000 == 0x7800000000000000 {
		return sign, 0, 0, specialInf
	}
	if b&0x6000000000000000 == 0x6000000000000000 {
		exp = int((b>>51)&0x3FF) - 398
		coeff = (b & 0x0007FFFFFFFFFFFF) | 0x0020000000000000
	} else {
		exp = int((b>>53)&0x3FF) - 398
		coeff = b & 0x001FFFFFFFFFFFFF
	}
	return
}

// bid128Unpack extracts sign, biased exponent, coefficient (as [2]uint64),
// and special value flag from a BID128-encoded pair.
func bid128Unpack(lo, hi uint64) (sign int, exp int, coeff [2]uint64, special int) {
	sign = int(hi >> 63)
	if hi&0x7c00000000000000 == 0x7c00000000000000 {
		return sign, 0, [2]uint64{}, specialNaN
	}
	if hi&0x7c00000000000000 == 0x7800000000000000 {
		return sign, 0, [2]uint64{}, specialInf
	}
	if hi&0x6000000000000000 == 0x6000000000000000 {
		exp = int((hi>>47)&0x3FFF) - 6176
		coeff = [2]uint64{lo, (1 << 49) | (hi & ((1 << 47) - 1))}
	} else {
		exp = int((hi>>49)&0x3FFF) - 6176
		coeff = [2]uint64{lo, hi & ((1 << 49) - 1)}
	}
	return
}

func appendSpecial(dst []byte, sign int, special int) []byte {
	switch special {
	case specialNaN:
		return append(dst, "NaN"...)
	case specialInf:
		if sign != 0 {
			return append(dst, "-Inf"...)
		}
		return append(dst, "+Inf"...)
	}
	return dst
}

// appendDecimalDigits formats a decimal value (sign, exp, coeff) where
// the value is (-1)^sign * coeff * 10^exp.
func appendDecimalDigits(dst []byte, sign int, exp int, coeff uint64, format byte, prec int) []byte {
	if coeff == 0 {
		if sign != 0 {
			dst = append(dst, '-')
		}
		if format == 'e' || format == 'E' {
			if prec <= 0 {
				return append(dst, "0e+00"...)
			}
			dst = append(dst, "0."...)
			for i := 0; i < prec; i++ {
				dst = append(dst, '0')
			}
			return append(dst, "e+00"...)
		}
		if prec <= 0 {
			return append(dst, '0')
		}
		dst = append(dst, "0."...)
		for i := 0; i < prec; i++ {
			dst = append(dst, '0')
		}
		return dst
	}

	// Extract digits.
	var digits [20]byte // max 16 digits for BID64
	ndigits := 0
	c := coeff
	for c > 0 {
		digits[ndigits] = byte(c%10) + '0'
		c /= 10
		ndigits++
	}
	// Reverse to most-significant first.
	for i, j := 0, ndigits-1; i < j; i, j = i+1, j-1 {
		digits[i], digits[j] = digits[j], digits[i]
	}

	return formatDigits(dst, sign, exp, digits[:ndigits], format, prec)
}

// appendDecimalDigits128 is the same as appendDecimalDigits but for 128-bit coefficients.
func appendDecimalDigits128(dst []byte, sign int, exp int, coeff [2]uint64, format byte, prec int) []byte {
	lo, hi := coeff[0], coeff[1]
	if hi == 0 && lo == 0 {
		return appendDecimalDigits(dst, sign, exp, 0, format, prec)
	}
	// If the coefficient fits in uint64, use the simpler path.
	if hi == 0 {
		return appendDecimalDigits(dst, sign, exp, lo, format, prec)
	}

	// Extract digits from uint128 coefficient via repeated divmod by 10.
	var digits [40]byte // max 34 digits for BID128
	ndigits := 0
	for hi > 0 || lo > 0 {
		// Divide [hi:lo] by 10, producing quotient [qhi:qlo] and remainder.
		qhi := hi / 10
		rem := hi % 10
		// Now divide (rem * 2^64 + lo) by 10.
		// rem is at most 9, so rem * 2^64 + lo fits in conceptual 128 bits.
		// We split: (rem * 2^64 + lo) / 10
		//   = (rem * 1844674407370955161) + (rem * 6 + lo) / 10
		mid := rem * 1844674407370955161 // rem * (2^64 / 10), truncated
		partial := rem*6 + lo            // rem * (2^64 mod 10) + lo
		qlo := mid + partial/10
		digit := partial % 10

		digits[ndigits] = byte(digit) + '0'
		ndigits++
		hi, lo = qhi, qlo
	}
	// Reverse to most-significant first.
	for i, j := 0, ndigits-1; i < j; i, j = i+1, j-1 {
		digits[i], digits[j] = digits[j], digits[i]
	}

	return formatDigits(dst, sign, exp, digits[:ndigits], format, prec)
}

// formatDigits formats a decimal number given sign, exponent, and a digit string.
func formatDigits(dst []byte, sign int, exp int, digits []byte, format byte, prec int) []byte {
	ndigits := len(digits)

	if prec < 0 {
		// Shortest representation: strip trailing zeros.
		for ndigits > 0 && digits[ndigits-1] == '0' {
			ndigits--
			exp++
		}
		digits = digits[:ndigits]
	}

	if sign != 0 {
		dst = append(dst, '-')
	}

	switch format {
	case 'e', 'E':
		return appendExp(dst, digits, exp, format, prec)
	case 'f':
		return appendFixed(dst, digits, exp, prec)
	case 'g', 'G', 0:
		// 'g' uses 'e' for large/small exponents, 'f' otherwise.
		e := exp + ndigits - 1
		if prec < 0 {
			// Shortest: switch to scientific for very large/small values.
			if e < -4 || e >= ndigits {
				ef := byte('e')
				if format == 'G' {
					ef = 'E'
				}
				return appendExp(dst, digits, exp, ef, -1)
			}
			return appendFixed(dst, digits, exp, -1)
		}
		p := prec
		if p == 0 {
			p = 1
		}
		if e >= -4 && e < p {
			return appendFixed(dst, digits, exp, p-ndigits-exp)
		}
		ef := byte('e')
		if format == 'G' {
			ef = 'E'
		}
		return appendExp(dst, digits, exp, ef, p-1)
	default:
		// Unknown format, default to 'g'.
		// Undo the sign we appended above.
		if sign != 0 {
			dst = dst[:len(dst)-1]
		}
		return formatDigits(dst, sign, exp, digits, 'g', prec)
	}
}

// appendFixed formats in fixed-point notation.
func appendFixed(dst []byte, digits []byte, exp int, prec int) []byte {
	ndigits := len(digits)
	// intPart = ndigits + exp (digits before the decimal point)
	intPart := ndigits + exp

	if prec < 0 {
		// Shortest: use all digits.
	} else {
		// Truncate/extend digit string so that exactly prec digits
		// appear after the decimal point.
		need := intPart + prec // total digits we need
		if need <= 0 {
			// All digits are beyond the precision window.
			digits = digits[:0]
			ndigits = 0
		} else if need < ndigits {
			digits = digits[:need]
			ndigits = need
		}
		// (if need > ndigits, we'll pad with zeros below)
	}

	if intPart <= 0 {
		// 0.000...digits
		dst = append(dst, '0')
		if prec != 0 && (prec < 0 && ndigits > 0 || prec > 0) {
			dst = append(dst, '.')
			leading := -intPart
			if prec >= 0 && leading > prec {
				leading = prec
			}
			for i := 0; i < leading; i++ {
				dst = append(dst, '0')
			}
			dst = append(dst, digits...)
			if prec > 0 {
				written := leading + ndigits
				for written < prec {
					dst = append(dst, '0')
					written++
				}
			}
		}
	} else if intPart >= ndigits {
		// All digits are before the decimal point.
		dst = append(dst, digits...)
		for i := ndigits; i < intPart; i++ {
			dst = append(dst, '0')
		}
		if prec > 0 {
			dst = append(dst, '.')
			for i := 0; i < prec; i++ {
				dst = append(dst, '0')
			}
		}
	} else {
		// Decimal point within digits.
		dst = append(dst, digits[:intPart]...)
		if prec != 0 {
			dst = append(dst, '.')
			dst = append(dst, digits[intPart:]...)
			if prec > 0 {
				written := ndigits - intPart
				for written < prec {
					dst = append(dst, '0')
					written++
				}
			}
		}
	}
	return dst
}

// appendExp formats in scientific notation.
func appendExp(dst []byte, digits []byte, exp int, format byte, prec int) []byte {
	ndigits := len(digits)
	if ndigits == 0 {
		dst = append(dst, '0')
		if prec > 0 {
			dst = append(dst, '.')
			for i := 0; i < prec; i++ {
				dst = append(dst, '0')
			}
		}
		dst = append(dst, format)
		dst = append(dst, "+00"...)
		return dst
	}

	// Value is digits[0].digits[1:] × 10^e  where e = exp + ndigits - 1
	e := exp + ndigits - 1

	// Truncate to prec+1 significant digits if prec is specified.
	shown := ndigits
	if prec >= 0 && prec+1 < shown {
		shown = prec + 1
	}

	dst = append(dst, digits[0])
	fracDigits := shown - 1
	if prec > 0 || (prec < 0 && fracDigits > 0) {
		dst = append(dst, '.')
		dst = append(dst, digits[1:1+fracDigits]...)
		// Pad with zeros if needed.
		if prec > 0 {
			for i := fracDigits; i < prec; i++ {
				dst = append(dst, '0')
			}
		}
	}

	dst = append(dst, format)
	if e < 0 {
		dst = append(dst, '-')
		e = -e
	} else {
		dst = append(dst, '+')
	}
	if e >= 100 {
		dst = append(dst, byte(e/100)+'0')
	}
	if e >= 10 {
		dst = append(dst, byte(e/10%10)+'0')
	} else {
		dst = append(dst, '0')
	}
	dst = append(dst, byte(e%10)+'0')
	return dst
}

// --- Parsing ---

func parseDecimal64(s string) (decimal64, error) {
	if len(s) == 0 {
		return 0, ErrSyntax
	}

	// Handle special values.
	if hasPrefix(s, "NaN") || hasPrefix(s, "nan") {
		b := uint64(0x7c00000000000000)
		return *(*decimal64)(unsafe.Pointer(&b)), nil
	}

	neg := false
	if s[0] == '+' {
		s = s[1:]
	} else if s[0] == '-' {
		neg = true
		s = s[1:]
	}

	if hasPrefix(s, "Inf") || hasPrefix(s, "inf") || hasPrefix(s, "Infinity") || hasPrefix(s, "infinity") {
		b := uint64(0x7800000000000000)
		if neg {
			b |= 0x8000000000000000
		}
		return *(*decimal64)(unsafe.Pointer(&b)), nil
	}

	// Parse decimal digits.
	var coeff uint64
	exp := 0
	sawDot := false
	ndigits := 0
	fracDigits := 0

	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '.' {
			if sawDot {
				return 0, ErrSyntax
			}
			sawDot = true
			continue
		}
		if c == 'e' || c == 'E' {
			// Parse exponent.
			i++
			if i >= len(s) {
				return 0, ErrSyntax
			}
			eneg := false
			if s[i] == '+' {
				i++
			} else if s[i] == '-' {
				eneg = true
				i++
			}
			if i >= len(s) {
				return 0, ErrSyntax
			}
			eexp := 0
			for i < len(s) {
				if s[i] < '0' || s[i] > '9' {
					return 0, ErrSyntax
				}
				eexp = eexp*10 + int(s[i]-'0')
				i++
			}
			if eneg {
				eexp = -eexp
			}
			exp += eexp
			break
		}
		if c < '0' || c > '9' {
			return 0, ErrSyntax
		}
		if ndigits < 16 { // max 16 significant digits for BID64
			coeff = coeff*10 + uint64(c-'0')
			if coeff > 0 || ndigits > 0 {
				ndigits++
			}
		} else {
			exp++ // extra digits beyond precision
		}
		if sawDot {
			fracDigits++
		}
	}

	if ndigits == 0 && !sawDot {
		return 0, ErrSyntax
	}

	exp -= fracDigits

	return bid64Pack(neg, exp, coeff), nil
}

func parseDecimal128(s string) (decimal128, error) {
	// For now, parse via decimal64 and widen.
	// This limits precision to ~16 digits but is correct for the prototype.
	d64, err := parseDecimal64(s)
	if err != nil {
		return 0, err
	}
	return decimal128(d64), nil
}

// bid64Pack encodes a decimal64 value from sign, exponent, and coefficient.
func bid64Pack(neg bool, exp int, coeff uint64) decimal64 {
	biasedExp := exp + 398
	if biasedExp < 0 {
		biasedExp = 0
	}
	if biasedExp > 767 {
		biasedExp = 767
	}

	var b uint64
	if neg {
		b |= 0x8000000000000000
	}

	if coeff < 0x0020000000000000 {
		// Form 1: coefficient fits in 53 bits
		b |= uint64(biasedExp) << 53
		b |= coeff
	} else {
		// Form 2: large coefficient
		b |= 0x6000000000000000
		b |= uint64(biasedExp) << 51
		b |= coeff & 0x0007FFFFFFFFFFFF
	}

	return *(*decimal64)(unsafe.Pointer(&b))
}

func hasPrefix(s, prefix string) bool {
	return len(s) >= len(prefix) && s[:len(prefix)] == prefix
}
