// Copyright 2025 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package strconv

import (
	"math/bits"
	"unsafe"
)

// FormatDecimal converts a decimal128 value to a string.
// The format fmt and precision prec follow the same rules as [FormatFloat].
// The bitSize must be 64 for values from decimal64 or 128 for decimal128.
func FormatDecimal(d decimal128, fmt byte, prec int, bitSize int) string {
	return string(AppendDecimal(nil, d, fmt, prec, bitSize))
}

// AppendDecimal appends the string form of the decimal128 value d,
// as generated by FormatDecimal, to dst and returns the extended buffer.
// The bitSize must be 64 for values widened from decimal64 or 128 for decimal128.
func AppendDecimal(dst []byte, d decimal128, fmt byte, prec int, bitSize int) []byte {
	p := (*[2]uint64)(unsafe.Pointer(&d))
	lo, hi := p[0], p[1]
	sign, exp, coeff, special := bid128Unpack(lo, hi)
	if special != 0 {
		return appendSpecial(dst, sign, special)
	}
	_ = bitSize // reserved for future precision control
	return appendDecimalDigits128(dst, sign, exp, coeff, fmt, prec)
}

// FormatDecimal64 converts a decimal64 value to a string.
// The format fmt and precision prec follow the same rules as [FormatFloat].
func FormatDecimal64(d decimal64, fmt byte, prec int) string {
	return FormatDecimal(decimal128(d), fmt, prec, 64)
}

// AppendDecimal64 appends the string form of the decimal64 value d,
// as generated by FormatDecimal64, to dst and returns the extended buffer.
func AppendDecimal64(dst []byte, d decimal64, fmt byte, prec int) []byte {
	return AppendDecimal(dst, decimal128(d), fmt, prec, 64)
}

// FormatDecimal128 converts a decimal128 value to a string.
// The format fmt and precision prec follow the same rules as [FormatFloat].
func FormatDecimal128(d decimal128, fmt byte, prec int) string {
	return FormatDecimal(d, fmt, prec, 128)
}

// AppendDecimal128 appends the string form of the decimal128 value d,
// as generated by FormatDecimal128, to dst and returns the extended buffer.
func AppendDecimal128(dst []byte, d decimal128, fmt byte, prec int) []byte {
	return AppendDecimal(dst, d, fmt, prec, 128)
}

// ParseDecimal64 converts a string to a decimal64 value.
// It recognizes decimal floating-point literals, "NaN", "Inf", and "+Inf"/"-Inf".
func ParseDecimal64(s string) (decimal64, error) {
	d, err := parseDecimal64(s)
	if err != nil {
		return d, syntaxError("ParseDecimal64", s)
	}
	return d, nil
}

// ParseDecimal128 converts a string to a decimal128 value.
// It recognizes decimal floating-point literals, "NaN", "Inf", and "+Inf"/"-Inf".
func ParseDecimal128(s string) (decimal128, error) {
	d, err := parseDecimal128(s)
	if err != nil {
		return d, syntaxError("ParseDecimal128", s)
	}
	return d, nil
}

// --- BID64 unpacking ---

const (
	specialNaN = 1
	specialInf = 2
)

// bid64Unpack extracts sign, biased exponent, coefficient, and special value flag
// from a BID64-encoded uint64.
func bid64Unpack(b uint64) (sign int, exp int, coeff uint64, special int) {
	sign = int(b >> 63)
	if b&0x7c00000000000000 == 0x7c00000000000000 {
		return sign, 0, 0, specialNaN
	}
	if b&0x7800000000000000 == 0x7800000000000000 {
		return sign, 0, 0, specialInf
	}
	if b&0x6000000000000000 == 0x6000000000000000 {
		exp = int((b>>51)&0x3FF) - 398
		coeff = (b & 0x0007FFFFFFFFFFFF) | 0x0020000000000000
	} else {
		exp = int((b>>53)&0x3FF) - 398
		coeff = b & 0x001FFFFFFFFFFFFF
	}
	return
}

// bid128Unpack extracts sign, biased exponent, coefficient (as [2]uint64),
// and special value flag from a BID128-encoded pair.
func bid128Unpack(lo, hi uint64) (sign int, exp int, coeff [2]uint64, special int) {
	sign = int(hi >> 63)
	if hi&0x7c00000000000000 == 0x7c00000000000000 {
		return sign, 0, [2]uint64{}, specialNaN
	}
	if hi&0x7c00000000000000 == 0x7800000000000000 {
		return sign, 0, [2]uint64{}, specialInf
	}
	if hi&0x6000000000000000 == 0x6000000000000000 {
		exp = int((hi>>47)&0x3FFF) - 6176
		coeff = [2]uint64{lo, (1 << 49) | (hi & ((1 << 47) - 1))}
	} else {
		exp = int((hi>>49)&0x3FFF) - 6176
		coeff = [2]uint64{lo, hi & ((1 << 49) - 1)}
	}
	return
}

func appendSpecial(dst []byte, sign int, special int) []byte {
	switch special {
	case specialNaN:
		return append(dst, "NaN"...)
	case specialInf:
		if sign != 0 {
			return append(dst, "-Inf"...)
		}
		return append(dst, "+Inf"...)
	}
	return dst
}

// appendDecimalDigits formats a decimal value (sign, exp, coeff) where
// the value is (-1)^sign * coeff * 10^exp.
func appendDecimalDigits(dst []byte, sign int, exp int, coeff uint64, format byte, prec int) []byte {
	if coeff == 0 {
		if sign != 0 {
			dst = append(dst, '-')
		}
		switch format {
		case 'e', 'E':
			if prec <= 0 {
				dst = append(dst, '0', format)
				return append(dst, "+00"...)
			}
			dst = append(dst, "0."...)
			for i := 0; i < prec; i++ {
				dst = append(dst, '0')
			}
			dst = append(dst, format)
			return append(dst, "+00"...)
		case 'g', 'G':
			// %g strips trailing zeros, so zero is always "0".
			// The fmt layer's # flag restores trailing zeros if needed.
			return append(dst, '0')
		default: // 'f'
			if prec <= 0 {
				return append(dst, '0')
			}
			dst = append(dst, "0."...)
			for i := 0; i < prec; i++ {
				dst = append(dst, '0')
			}
			return dst
		}
	}

	// Extract digits.
	var digits [20]byte // max 16 digits for BID64
	ndigits := 0
	c := coeff
	for c > 0 {
		digits[ndigits] = byte(c%10) + '0'
		c /= 10
		ndigits++
	}
	// Reverse to most-significant first.
	for i, j := 0, ndigits-1; i < j; i, j = i+1, j-1 {
		digits[i], digits[j] = digits[j], digits[i]
	}

	return formatDigits(dst, sign, exp, digits[:ndigits], format, prec)
}

// appendDecimalDigits128 is the same as appendDecimalDigits but for 128-bit coefficients.
func appendDecimalDigits128(dst []byte, sign int, exp int, coeff [2]uint64, format byte, prec int) []byte {
	lo, hi := coeff[0], coeff[1]
	if hi == 0 && lo == 0 {
		return appendDecimalDigits(dst, sign, exp, 0, format, prec)
	}
	// If the coefficient fits in uint64, use the simpler path.
	if hi == 0 {
		return appendDecimalDigits(dst, sign, exp, lo, format, prec)
	}

	// Extract digits from uint128 coefficient via repeated divmod by 10.
	var digits [40]byte // max 34 digits for BID128
	ndigits := 0
	for hi > 0 || lo > 0 {
		// Divide [hi:lo] by 10, producing quotient [qhi:qlo] and remainder.
		qhi := hi / 10
		rem := hi % 10
		// Now divide (rem * 2^64 + lo) by 10.
		// rem is at most 9, so rem * 2^64 + lo fits in conceptual 128 bits.
		// We split: (rem * 2^64 + lo) / 10
		//   = (rem * 1844674407370955161) + (rem * 6 + lo) / 10
		mid := rem * 1844674407370955161 // rem * (2^64 / 10), truncated
		partial := rem*6 + lo            // rem * (2^64 mod 10) + lo
		qlo := mid + partial/10
		digit := partial % 10

		digits[ndigits] = byte(digit) + '0'
		ndigits++
		hi, lo = qhi, qlo
	}
	// Reverse to most-significant first.
	for i, j := 0, ndigits-1; i < j; i, j = i+1, j-1 {
		digits[i], digits[j] = digits[j], digits[i]
	}

	return formatDigits(dst, sign, exp, digits[:ndigits], format, prec)
}

// roundDigits rounds a digit string to n digits using half-even rounding.
// It returns the (possibly shortened) digit string and an exponent adjustment
// if rounding caused a carry (e.g. "999" rounded to 2 digits → "10", adj=1).
func roundDigits(digits []byte, n int) ([]byte, int) {
	if n >= len(digits) {
		return digits, 0
	}
	if n < 0 {
		n = 0
	}

	// Check if we need to round up.
	roundUp := false
	if n < len(digits) {
		d := digits[n]
		if d > '5' {
			roundUp = true
		} else if d == '5' {
			// Round half to even: round up if preceding digit is odd,
			// or if there are any non-zero digits after the '5'.
			if n > 0 && (digits[n-1]-'0')%2 != 0 {
				roundUp = true
			} else {
				for i := n + 1; i < len(digits); i++ {
					if digits[i] != '0' {
						roundUp = true
						break
					}
				}
			}
		}
	}

	digits = digits[:n]
	if !roundUp {
		return digits, 0
	}

	// Propagate carry.
	for i := n - 1; i >= 0; i-- {
		if digits[i] < '9' {
			digits[i]++
			return digits, 0
		}
		digits[i] = '0'
	}

	// All digits were 9 and carried over: result is "1" with exponent +1.
	if n > 0 {
		digits[0] = '1'
		digits = digits[:1]
	}
	return digits, 1
}

// formatDigits formats a decimal number given sign, exponent, and a digit string.
func formatDigits(dst []byte, sign int, exp int, digits []byte, format byte, prec int) []byte {
	ndigits := len(digits)

	if prec == -1 {
		// Shortest representation: strip trailing zeros.
		for ndigits > 0 && digits[ndigits-1] == '0' {
			ndigits--
			exp++
		}
		digits = digits[:ndigits]
	}

	if sign != 0 {
		dst = append(dst, '-')
	}

	switch format {
	case 'e', 'E':
		return appendExp(dst, digits, exp, format, prec)
	case 'f':
		return appendFixed(dst, digits, exp, prec)
	case 'g', 'G', 0:
		// 'g' uses 'e' for large/small exponents, 'f' otherwise.
		// Trailing zeros and trailing decimal points are stripped.
		ef := byte('e')
		if format == 'G' {
			ef = 'E'
		}
		e := exp + ndigits - 1
		if prec < 0 {
			// Shortest: pick whichever of 'e' or 'f' is shorter.
			useSci := false
			if e < -4 {
				useSci = true
			} else if exp > 0 {
				// Integer with trailing zeros (e.g., 1000 = 1×10^3).
				// Compare lengths: fixed "1000" (e+1) vs scientific "1e+03" (varies).
				fixedLen := e + 1
				sciLen := 1 // leading digit
				if ndigits > 1 {
					sciLen += 1 + ndigits - 1 // '.' + frac digits
				}
				sciLen += 2 // 'e' + sign
				ae := e
				if ae < 0 {
					ae = -ae
				}
				if ae >= 100 {
					sciLen += 3
				} else {
					sciLen += 2
				}
				useSci = sciLen < fixedLen
			}
			if prec == -1 {
				// Normalized shortest: strip trailing zeros from result.
				if useSci {
					return stripTrailingZeros(appendExp(dst, digits, exp, ef, -1))
				}
				return stripTrailingZeros(appendFixed(dst, digits, exp, -1))
			}
			// Quantum-preserving (prec == -2): keep coefficient's trailing zeros.
			if useSci {
				return appendExp(dst, digits, exp, ef, -1)
			}
			return appendFixed(dst, digits, exp, -1)
		}
		p := prec
		if p == 0 {
			p = 1
		}
		// Round to p significant digits.
		if p < ndigits {
			var adj int
			digits, adj = roundDigits(digits, p)
			exp += ndigits - len(digits) + adj
			ndigits = len(digits)
			e = exp + ndigits - 1
		}
		if e >= -4 && e < p {
			return stripTrailingZeros(appendFixed(dst, digits, exp, p-ndigits-exp))
		}
		return stripTrailingZeros(appendExp(dst, digits, exp, ef, p-1))
	default:
		// Unknown format, default to 'g'.
		// Undo the sign we appended above.
		if sign != 0 {
			dst = dst[:len(dst)-1]
		}
		return formatDigits(dst, sign, exp, digits, 'g', prec)
	}
}

// appendFixed formats in fixed-point notation.
func appendFixed(dst []byte, digits []byte, exp int, prec int) []byte {
	ndigits := len(digits)
	// intPart = ndigits + exp (digits before the decimal point)
	intPart := ndigits + exp

	if prec < 0 {
		// Shortest: use all digits.
	} else {
		// Round/extend digit string so that exactly prec digits
		// appear after the decimal point.
		need := intPart + prec // total digits we need
		if need <= 0 {
			if need == 0 && ndigits > 0 {
				// All digits are fractional. Decide whether to round to 0 or 1
				// using half-even (banker's) rounding.
				d := digits[0]
				roundUp := false
				if d > '5' {
					roundUp = true
				} else if d == '5' {
					// Exact tie: round up only if there are non-zero trailing
					// digits. The preceding integer digit is implicitly 0 (even),
					// so on an exact tie we don't round up.
					for i := 1; i < ndigits; i++ {
						if digits[i] != '0' {
							roundUp = true
							break
						}
					}
				}
				if roundUp {
					digits = []byte{'1'}
					ndigits = 1
					intPart++
				} else {
					digits = digits[:0]
					ndigits = 0
				}
			} else {
				digits = digits[:0]
				ndigits = 0
			}
		} else if need < ndigits {
			var adj int
			digits, adj = roundDigits(digits, need)
			ndigits = len(digits)
			if adj > 0 {
				// Carry increased the number of integer digits.
				intPart += adj
				// Pad to maintain intPart + prec = ndigits relationship.
				// After carry, digits is "1" with len 1, but we need
				// intPart + prec total digits.
				for ndigits < intPart+prec {
					digits = append(digits, '0')
					ndigits++
				}
			}
		}
		// (if need > ndigits, we'll pad with zeros below)
	}

	if intPart <= 0 {
		// 0.000...digits
		dst = append(dst, '0')
		if prec != 0 && (prec < 0 && ndigits > 0 || prec > 0) {
			dst = append(dst, '.')
			leading := -intPart
			if prec >= 0 && leading > prec {
				leading = prec
			}
			for i := 0; i < leading; i++ {
				dst = append(dst, '0')
			}
			dst = append(dst, digits...)
			if prec > 0 {
				written := leading + ndigits
				for written < prec {
					dst = append(dst, '0')
					written++
				}
			}
		}
	} else if intPart >= ndigits {
		// All digits are before the decimal point.
		dst = append(dst, digits...)
		for i := ndigits; i < intPart; i++ {
			dst = append(dst, '0')
		}
		if prec > 0 {
			dst = append(dst, '.')
			for i := 0; i < prec; i++ {
				dst = append(dst, '0')
			}
		}
	} else {
		// Decimal point within digits.
		dst = append(dst, digits[:intPart]...)
		if prec != 0 {
			dst = append(dst, '.')
			dst = append(dst, digits[intPart:]...)
			if prec > 0 {
				written := ndigits - intPart
				for written < prec {
					dst = append(dst, '0')
					written++
				}
			}
		}
	}
	return dst
}

// appendExp formats in scientific notation.
func appendExp(dst []byte, digits []byte, exp int, format byte, prec int) []byte {
	ndigits := len(digits)
	if ndigits == 0 {
		dst = append(dst, '0')
		if prec > 0 {
			dst = append(dst, '.')
			for i := 0; i < prec; i++ {
				dst = append(dst, '0')
			}
		}
		dst = append(dst, format)
		dst = append(dst, "+00"...)
		return dst
	}

	// Value is digits[0].digits[1:] × 10^e  where e = exp + ndigits - 1
	e := exp + ndigits - 1

	// Round to prec+1 significant digits if prec is specified.
	shown := ndigits
	if prec >= 0 && prec+1 < ndigits {
		var adj int
		digits, adj = roundDigits(digits, prec+1)
		ndigits = len(digits)
		shown = ndigits
		e += adj
	}

	dst = append(dst, digits[0])
	fracDigits := shown - 1
	if prec > 0 || (prec < 0 && fracDigits > 0) {
		dst = append(dst, '.')
		dst = append(dst, digits[1:1+fracDigits]...)
		// Pad with zeros if needed.
		if prec > 0 {
			for i := fracDigits; i < prec; i++ {
				dst = append(dst, '0')
			}
		}
	}

	dst = append(dst, format)
	if e < 0 {
		dst = append(dst, '-')
		e = -e
	} else {
		dst = append(dst, '+')
	}
	// BID128 exponents can reach ~6176, requiring up to 4 digits.
	if e >= 1000 {
		dst = append(dst, byte(e/1000)+'0')
	}
	if e >= 100 {
		dst = append(dst, byte(e/100%10)+'0')
	}
	if e >= 10 {
		dst = append(dst, byte(e/10%10)+'0')
	} else {
		dst = append(dst, '0')
	}
	dst = append(dst, byte(e%10)+'0')
	return dst
}

// stripTrailingZeros removes trailing zeros after a decimal point,
// and the decimal point itself if no fractional digits remain.
// It handles scientific notation (e.g., "1.230e+02" → "1.23e+02").
func stripTrailingZeros(dst []byte) []byte {
	// Find the exponent part if present.
	expIdx := -1
	for i := len(dst) - 1; i >= 0; i-- {
		if dst[i] == 'e' || dst[i] == 'E' {
			expIdx = i
			break
		}
	}

	// Find decimal point.
	dotIdx := -1
	end := len(dst)
	if expIdx >= 0 {
		end = expIdx
	}
	for i := 0; i < end; i++ {
		if dst[i] == '.' {
			dotIdx = i
			break
		}
	}
	if dotIdx < 0 {
		return dst // no decimal point, nothing to strip
	}

	// Strip trailing zeros from fractional part (before exponent if present).
	stripTo := end
	for stripTo > dotIdx+1 && dst[stripTo-1] == '0' {
		stripTo--
	}
	// Remove decimal point if no fractional digits remain.
	if stripTo == dotIdx+1 {
		stripTo = dotIdx
	}

	if stripTo == end {
		return dst // nothing stripped
	}

	// Rebuild: dst[:stripTo] + dst[expIdx:]
	if expIdx >= 0 {
		tail := append([]byte(nil), dst[expIdx:]...)
		dst = append(dst[:stripTo], tail...)
	} else {
		dst = dst[:stripTo]
	}
	return dst
}

// --- Parsing ---

func parseDecimal64(s string) (decimal64, error) {
	if len(s) == 0 {
		return 0, ErrSyntax
	}

	// Handle special values.
	if hasPrefix(s, "NaN") || hasPrefix(s, "nan") {
		b := uint64(0x7c00000000000000)
		return *(*decimal64)(unsafe.Pointer(&b)), nil
	}

	neg := false
	if s[0] == '+' {
		s = s[1:]
	} else if s[0] == '-' {
		neg = true
		s = s[1:]
	}

	if hasPrefix(s, "Inf") || hasPrefix(s, "inf") || hasPrefix(s, "Infinity") || hasPrefix(s, "infinity") {
		b := uint64(0x7800000000000000)
		if neg {
			b |= 0x8000000000000000
		}
		return *(*decimal64)(unsafe.Pointer(&b)), nil
	}

	// Parse decimal digits.
	var coeff uint64
	exp := 0
	sawDot := false
	sawDigit := false
	ndigits := 0
	fracDigits := 0

	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '.' {
			if sawDot {
				return 0, ErrSyntax
			}
			sawDot = true
			continue
		}
		if c == 'e' || c == 'E' {
			// Parse exponent.
			i++
			if i >= len(s) {
				return 0, ErrSyntax
			}
			eneg := false
			if s[i] == '+' {
				i++
			} else if s[i] == '-' {
				eneg = true
				i++
			}
			if i >= len(s) {
				return 0, ErrSyntax
			}
			eexp := 0
			for i < len(s) {
				if s[i] < '0' || s[i] > '9' {
					return 0, ErrSyntax
				}
				eexp = eexp*10 + int(s[i]-'0')
				i++
			}
			if eneg {
				eexp = -eexp
			}
			exp += eexp
			break
		}
		if c < '0' || c > '9' {
			return 0, ErrSyntax
		}
		sawDigit = true
		if ndigits < 16 { // max 16 significant digits for BID64
			coeff = coeff*10 + uint64(c-'0')
			if coeff > 0 || ndigits > 0 {
				ndigits++
			}
		} else {
			exp++ // extra digits beyond precision
		}
		if sawDot {
			fracDigits++
		}
	}

	if !sawDigit {
		return 0, ErrSyntax
	}

	exp -= fracDigits

	return bid64Pack(neg, exp, coeff), nil
}

func parseDecimal128(s string) (decimal128, error) {
	if len(s) == 0 {
		return 0, ErrSyntax
	}

	// Handle special values.
	if hasPrefix(s, "NaN") || hasPrefix(s, "nan") {
		hi := uint64(0x7c00000000000000)
		return *(*decimal128)(unsafe.Pointer(&[2]uint64{0, hi})), nil
	}

	neg := false
	if s[0] == '+' {
		s = s[1:]
	} else if s[0] == '-' {
		neg = true
		s = s[1:]
	}

	if hasPrefix(s, "Inf") || hasPrefix(s, "inf") || hasPrefix(s, "Infinity") || hasPrefix(s, "infinity") {
		hi := uint64(0x7800000000000000)
		if neg {
			hi |= 0x8000000000000000
		}
		return *(*decimal128)(unsafe.Pointer(&[2]uint64{0, hi})), nil
	}

	// Parse decimal digits into a uint128 coefficient [coeffHi:coeffLo].
	var coeffHi, coeffLo uint64
	exp := 0
	sawDot := false
	sawDigit := false
	ndigits := 0
	fracDigits := 0

	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '.' {
			if sawDot {
				return 0, ErrSyntax
			}
			sawDot = true
			continue
		}
		if c == 'e' || c == 'E' {
			i++
			if i >= len(s) {
				return 0, ErrSyntax
			}
			eneg := false
			if s[i] == '+' {
				i++
			} else if s[i] == '-' {
				eneg = true
				i++
			}
			if i >= len(s) {
				return 0, ErrSyntax
			}
			eexp := 0
			for i < len(s) {
				if s[i] < '0' || s[i] > '9' {
					return 0, ErrSyntax
				}
				eexp = eexp*10 + int(s[i]-'0')
				i++
			}
			if eneg {
				eexp = -eexp
			}
			exp += eexp
			break
		}
		if c < '0' || c > '9' {
			return 0, ErrSyntax
		}
		sawDigit = true
		if ndigits < 34 { // max 34 significant digits for BID128
			// [coeffHi:coeffLo] = [coeffHi:coeffLo] * 10 + digit
			mulHi, mulLo := bits.Mul64(coeffLo, 10)
			coeffHi = coeffHi*10 + mulHi
			d := uint64(c - '0')
			newLo := mulLo + d
			if newLo < mulLo {
				coeffHi++
			}
			coeffLo = newLo
			if coeffHi > 0 || coeffLo > 0 || ndigits > 0 {
				ndigits++
			}
		} else {
			exp++
		}
		if sawDot {
			fracDigits++
		}
	}

	if !sawDigit {
		return 0, ErrSyntax
	}

	exp -= fracDigits

	return bid128Pack128(neg, exp, coeffHi, coeffLo), nil
}

// bid128Pack128 encodes a decimal128 value from sign, exponent, and uint128 coefficient.
func bid128Pack128(neg bool, exp int, coeffHi, coeffLo uint64) decimal128 {
	const bias = 6176
	biasedExp := exp + bias
	if biasedExp < 0 {
		biasedExp = 0
	}
	if biasedExp > 0x3FFF {
		biasedExp = 0x3FFF
	}

	var hi uint64
	if neg {
		hi |= 1 << 63
	}

	if coeffHi < (1 << 49) {
		// Form 1: coefficient high word fits in 49 bits.
		hi |= uint64(biasedExp)<<49 | coeffHi
	} else {
		// Form 2: coefficient high word >= 2^49.
		hi |= (3 << 61) | uint64(biasedExp)<<47 | (coeffHi & ((1 << 47) - 1))
	}

	return *(*decimal128)(unsafe.Pointer(&[2]uint64{coeffLo, hi}))
}

// bid64Pack encodes a decimal64 value from sign, exponent, and coefficient.
func bid64Pack(neg bool, exp int, coeff uint64) decimal64 {
	biasedExp := exp + 398
	if biasedExp < 0 {
		biasedExp = 0
	}
	if biasedExp > 767 {
		biasedExp = 767
	}

	var b uint64
	if neg {
		b |= 0x8000000000000000
	}

	if coeff < 0x0020000000000000 {
		// Form 1: coefficient fits in 53 bits
		b |= uint64(biasedExp) << 53
		b |= coeff
	} else {
		// Form 2: large coefficient
		b |= 0x6000000000000000
		b |= uint64(biasedExp) << 51
		b |= coeff & 0x0007FFFFFFFFFFFF
	}

	return *(*decimal64)(unsafe.Pointer(&b))
}

func hasPrefix(s, prefix string) bool {
	return len(s) >= len(prefix) && s[:len(prefix)] == prefix
}
